apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: arbeidsplassen
  name: arbeidsplassen_no-tests
  namespace: arbeidsplassen
spec:
  schedule: "* * * * *"
  image: {{ image }}
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
  spec:
    accessPolicy:
      outbound:
        external:
          - host: arbeidsplassen.nav.no
          - host: arbeidsplassen.intern.dev.nav.no